package net.amber.culminating;

import java.util.Arrays;

public class Background {
    protected String bkgrdName;
    protected String bonusEquipment;
    protected String bkgrdFeatureName;
    protected String bkgrdFeature;
    protected double startingGold;
    protected String bkgrdDescription;
    protected Skill[] proficientSkills;
    protected String toolProficiencies;
    protected String languageProficiencies;
    protected boolean hasOptionalProficiencies;
    protected Skill[] optionalProficiencies;
    protected int optionalProficiencyChoices;

    public Background(String name, String bE, String featureName, String feature, double sG, String desc, Skill[] skills, String tools, String langs, boolean hOP, Skill[] optionalProfs, int opProfChoices) {
        bkgrdName = name;
        bonusEquipment = bE;
        bkgrdFeatureName = featureName;
        bkgrdFeature = feature;
        startingGold = sG;
        bkgrdDescription = desc;
        proficientSkills = skills;
        toolProficiencies = tools;
        languageProficiencies = langs;
        for (Skill skl:proficientSkills) {
            skl.setProf(true);
        }
        hasOptionalProficiencies = hOP;
        optionalProficiencies = optionalProfs;
        optionalProficiencyChoices = opProfChoices;
    }

    public String getBkgrdName() {
        return bkgrdName;
    }

    public void setOptionalProficiency(PlayerCharacter p, String sklName) {
        Skill skl = null;
        for (Skill e:optionalProficiencies) {
            if (sklName.equalsIgnoreCase(e.getName()))
                skl = e;
        }
        p.setSkillProf(skl, true);
    }

    public Skill[] getOptionalProficiencies() {
        return optionalProficiencies;
    }

    public String toString() {
        return bkgrdName;
    }
    public String exportBackground() {
        return "Background: " + bkgrdName + "\n" +
                bkgrdDescription + "\n" +
                "Feature: " + bkgrdFeatureName + "\n" +
                bkgrdFeature + "\n" +
                "Starting Gold: " + startingGold + "\n" +
                "Skill Proficiencies: " + Arrays.toString(proficientSkills) + "\n" +
                "Tool Proficiencies: " + toolProficiencies + "\n" +
                "Language Proficiencies: " + languageProficiencies + "\n" +
                "Bonus Equipment: " + bonusEquipment;
    }
}

class Acolyte extends Background {
    public Acolyte() {
        super("Acolyte", "A holy symbol (a gift to you when you entered the priesthood), a prayer book or prayer wheel, 5 sticks of incense, vestments, a set of common clothes", "Shelter of the Faithful", "As an acolyte, you command the respect of those who share your faith, and you can perform the religious ceremonies of your deity. You and your adventuring companions can expect to receive free healing and care at a temple, shrine, or other established presence of your faith, though you must provide any material components needed for spells. Those who share your religion will support you (but only you) at a modest lifestyle. You might also have ties to a specific temple dedicated to your chosen deity or pantheon, and you have a residence there. This could be the temple where you used to serve, if you remain on good terms with it, or a temple where you have found a new home. While near your temple, you can call upon the priests for assistance, provided the assistance you ask for is not hazardous and you remain in good standing with your temple.", 15, "You have spent your life in the service of a temple to a specific god or pantheon of gods. You act as an intermediary between the realm of the holy and the mortal world, performing sacred rites and offering sacrifices in order to conduct worshipers into the presence of the divine. You are not necessarily a cleric--performing sacred rites is not the same thing as channeling divine power.", new Skill[]{new Insight(), new Religion()}, "none", "2 languages of choice", false, new Skill[0], 0);
    }
}

class Anthropologist extends Background {
    public Anthropologist() {
        super("Anthropologist", "A leather-bound diary, a bottle of ink, an ink pen, a set of traveler's clothes, one trinket of special significance", "Cultural Chameleon", "Before becoming an adventurer, you spent much of your adult life away from your homeland, living among people different from your kin. You came to understand these foreign cultures and the ways of their people, who eventually treated you as one of their own. One culture had more of an influence on you than any other, shaping your beliefs and customs. Choose a race whose culture you've adopted.", 10, "You have always been fascinated by other cultures, from the most ancient and primeval lost lands to the most modern civilizations. By studying other cultures' customs, philosophies, laws, rituals, religious beliefs, languages, and art, you have learned how tribes, empires, and all forms of society in between craft their own destinies and doom. This knowledge came to you not only through books and scrolls, but also through firsthand observation – by visiting far-flung settlements and exploring local histories and customs.", new Skill[]{new Insight(), new Religion()}, "none", "2 languages of choice", false, new Skill[0], 0);
    }
}

class Archaeologist extends Background {
    public Archaeologist() {
        super("Archaeologist", "A wooden case containing a map to a ruin or dungeon, a bullseye lantern, a miner's pick, a set of traveler's clothes, a shovel, a two-person tent, a trinket recovered from a dig site", "Historical Knowledge", "When you enter a ruin or dungeon, you can correctly ascertain its original purpose and determine its builders, whether those were dwarves, elves, humans, yuan-ti, or some other known race. In addition, you can determine the monetary value of art objects more than a century old.", 25, "An archaeologist learns about the long-lost and fallen cultures of the past by studying their remains – their bones, their ruins, their surviving masterworks, and their tombs. Those who practice archaeology travel to the far corners of the world to root through crumbled cities and lost dungeons, digging in search of artifacts that might tell the stories of monarchs and high priests, wars and cataclysms.", new Skill[]{new History(), new Survival()}, "Cartographer's tools or Navigator's tools", "1 language of choice", false, new Skill[0], 0);
    }
}

class Athlete extends Background {
    public Athlete() {
        super("Athlete", "A bronze discus or leather ball, a lucky charm or past trophy, a set of traveler's clothes", "Echoes of Victory", "You have attracted admiration among spectators, fellow athletes, and trainers in the region that hosted your past athletic victories. When visiting any settlement within 100 miles of where you grew up, there is a 50 percent chance you can find someone there who admires you and is willing to provide information and temporary shelter. Between adventures, you might compete in athletic events sufficient enough to maintain a comfortable lifestyle, as per the \"Practicing a Profession\" downtime activity in chapter 8 of the Players Handbook.", 10, "You strive to perfect yourself physically and in execution of everything you do. The thrill of competition lights fire in your blood, and the roar of the crowd drives you forward. Tales of your exploits precede you and might open doors or loosen tongues. Whether in one of the poleis, between them, or among the nonhuman peoples of Theros, physical contests and those who pursue them command respect bordering on reverence. Athletes arise from all walks of life and all cultures and quite often cross paths with one another.", new Skill[]{new Acrobatics(), new Athletics()}, "Vehicles (land)", "1 language of choice", false, new Skill[0], 0);
    }
}

class Charlatan extends Background {
    public Charlatan() {
        super("Charlatan", "A set of fine clothes, a disguise kit, tools of the con of your choice (ten stoppered bottles filled with colored liquid, a set of weighted dice, a deck of marked cards, or a signet ring of an imaginary duke)", "False Identity", "You have created a second identity that includes documentation, established acquaintances, and disguises that allow you to assume that persona. Additionally, you can forge documents including official papers and personal letters, as long as you have seen an example of the kind of document or the handwriting you are trying to copy.", 15, "You have always had a way with people. You know what makes them tick, you can tease out their hearts' desires after a few minutes of conversation, and with a few leading questions you can read them like they were children's books. It's a useful talent, and one that you're perfectly willing to use for your advantage.You know what people want and you deliver, or rather, you promise to deliver. Common sense should steer people away from things that sound too good to be true, but common sense seems to be in short supply when you're around. The bottle of pink colored liquid will surely cure that unseemly rash, this ointment -- nothing more than a bit of fat with a sprinkle of silver dust can restore youth and vigor, and there's a bridge in the city that just happens to be for sale. These marvels sound implausible, but you make them sound like the real deal.", new Skill[]{new Deception(), new SleightOfHand()}, "Disguise Kit and Forgery Kit", "none", false, new Skill[0], 0);
    }
}

class CityWatch extends Background {
    public CityWatch() {
        super("City Watch", "A uniform in the style of your unit and indicative of your rank, a horn with which to summon help, a set of manacles", "Watcher's Eye", "Your experience in enforcing the law, and dealing with lawbreakers, gives you a feel for local laws and criminals. You can easily find the local outpost of the watch or a similar organization, and just as easily pick out the dens of criminal activity in a community, although you're more likely to be welcome in the former locations rather than the latter.", 10, "You have served the community where you grew up, standing as its first line of defense against crime. You aren't a soldier, directing your gaze outward at possible enemies. Instead, your service to your hometown was to help police its populace, protecting the citizenry from lawbreakers and malefactors of every stripe. You might have been part of the City Watch of Waterdeep, the baton-wielding police force of the City of Splendors, protecting the common folk from thieves and rowdy nobility alike. Or you might have been one of the valiant defenders of Silverymoon, a member of the Silverwatch or even one of the magic-wielding Spellguard. Perhaps you hail from Neverwinter and have served as one of its Wintershield watchmen, the newly founded branch of guards who vow to keep safe the City of Skilled Hands.Even if you're not city-born or city-bred, this background can describe your early years as a member of law enforcement. Most settlements of any size have their own constables and police forces, and even smaller communities have sheriffs and bailiffs who stand ready to protect their community.", new Skill[]{new Athletics(), new Insight()}, "none", "2 languages of choice", false, new Skill[0], 0);
    }
}
class cwInvestigator extends Background {
    public cwInvestigator() {
        super("City Watch (Investigator)", "A uniform in the style of your unit and indicative of your rank, a horn with which to summon help, a set of manacles", "Watcher's Eye", "Your experience in enforcing the law, and dealing with lawbreakers, gives you a feel for local laws and criminals. You can easily find the local outpost of the watch or a similar organization, and just as easily pick out the dens of criminal activity in a community, although you're more likely to be welcome in the former locations rather than the latter.", 10, "You have served the community where you grew up, standing as its first line of defense against crime. You aren't a soldier, directing your gaze outward at possible enemies. Instead, your service to your hometown was to help police its populace, protecting the citizenry from lawbreakers and malefactors of every stripe. Even if you're not city-born or city-bred, this background can describe your early years as a member of law enforcement. Most settlements of any size have their own constables and police forces, and even smaller communities have sheriffs and bailiffs who stand ready to protect their community. Rarer than watch or patrol members are a community's investigators, you are responsible for solving crimes after the fact. Though such folk are seldom found in rural areas, nearly every settlement of decent size has at least one or two watch members who have the skill to investigate crime scenes and track down criminals.", new Skill[]{new Investigation(), new Insight()}, "none", "2 languages of choice", false, new Skill[0], 0);
    }
}

class ClanCrafter extends Background {
    public ClanCrafter() {
        super("Clan Crafter", " A set of artisan's tools with which you are proficient, a maker's mark chisel used to mark your handiwork with the symbol of the clan of crafters you learned your skill from, a set of traveler's clothes, a gem worth 10gp", "Respect of the Stout Folk", "As well respected as clan crafters are among outsiders, no one esteems them quite so highly as dwarves do. You always have free room and board in any place where shield dwarves or gold dwarves dwell, and the individuals in such a settlement might vie among themselves to determine who can offer you (and possibly your compatriots) the finest accommodations and assistance.", 5, "The Stout Folk are well known for their artisanship and the worth of their handiworks, and you have been trained in that ancient tradition. For years you labored under a dwarf master of the craft, enduring long hours and dismissive, sour-tempered treatment in order to gain the fine skills you possess today. You are most likely a dwarf, but not necessarily- particularly in the North, the shield dwarf clans learned long ago that only proud fools who are more concerned for their egos than their craft turn away promising apprentices, even those of other races. If you aren't a dwarf, however, you have taken a solemn oath never to take on an apprentice in the craft: it is not for non-dwarves to pass on the skills of Moradin's favored children. You would have no difficulty, however, finding a dwarf master who was willing to receive potential apprentices who came with your recommendation.", new Skill[]{new History(), new Insight()}, "1 type of artisan's tools", "Dwarvish (or 1 language of choice)", false, new Skill[0], 0);
    }
}

class CloisteredScholar extends Background {
    public CloisteredScholar() {
        super("Cloistered Scholar", "The scholar's robes of your cloister, a writing kit (small pouch with a quill, a bottle of ink, folded parchment, and a small penknife), a borrowed book on the subject of your current study", "Library Access", "Though others must often endure extensive interviews and significant fees to gain access to even the most common archives in your library, you have free and easy access to the majority of the library, though it might also have repositories of lore that are too valuable, magical, or secret to permit anyone immediate access. You have a working knowledge of your cloister's personnel and bureaucracy, and you know how to navigate those connections with some ease. Additionally, you are likely to gain preferential treatment at other libraries across the Realms, as professional courtesy shown to a fellow scholar.", 10, "As a child, you were inquisitive when your playmates were possessive or raucous. In your formative years, you found your way to one of Faerûn's great institutes of learning, where you were apprenticed and taught that knowledge is a more valuable treasure than gold or gems. Now you are ready to leave your home – not to abandon it, but to quest for new lore to add to its storehouse of knowledge. The most well-known of Faerûn's fonts of knowledge is Candlekeep. The great library is always in need of workers and attendants, some of whom rise through the ranks to assume roles of greater responsibility and prominence. You might be one of Candlekeep's own, dedicated to the curatorship of what is likely the most complete body of lore and history in all the world. Perhaps instead you were taken in by the scholars of the Vault of the Sages or the Map House in Silverymoon, and now you have struck out to increase your knowledge and to make yourself available to help those in other places who seek your expertise. You might be one of the few who aid Herald's Holdfast, helping to catalogue and maintain records of the information that arrives daily from across Faerûn.", new Skill[]{new History()}, "none", "2 languages of choice", true, new Skill[]{new Arcana(), new Nature(), new Religion()}, 1);
    }
}

class Courtier extends Background {
    public Courtier() {
        super("Courtier", "A set of fine clothes", "Court Functionary", "Your knowledge of how bureaucracies function lets you gain access to the records and inner workings of any noble court or government you encounter. You know who the movers and shakers are, whom to go to for the favors you seek, and what the current intrigues of interest in the group are.", 5, "In your earlier days, you were a personage of some significance in a noble court or a bureaucratic organization. You might or might not come from an upper-class family; your talents, rather than the circumstances of your birth, could have secured you this position. Even if you are no longer a full-fledged member of the group that gave you your start in life, your relationships with your former fellows can be an advantage for you and your adventuring comrades. You might undertake missions with your new companions that further the interest of the organization that gave you your start in life. In any event, the abilities that you honed while serving as a courtier will stand you in good stead as an adventurer.", new Skill[]{new Insight(), new Persuasion()}, "none", "2 of choice", false, new Skill[0], 0);
    }
}

class Criminal extends Background {
    public Criminal() {
        super("Criminal", "A crowbar, a set of dark common clothes including a hood", "Criminal Contact", "You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals. You know how to get messages to and from your contact, even over great distances; specifically, you know the local messengers, corrupt caravan masters, and seedy sailors who can deliver messages for you.", 15, "You are an experienced criminal with a history of breaking the law. You have spent a lot of time among other criminals and still have contacts within the criminal underworld. You're far closer than most people to the world of murder, theft, and violence that pervades the underbelly of civilization, and you have survived up to this point by flouting the rules and regulations of society.", new Skill[]{new Deception(), new Stealth()}, "1 type of gaming set and thieves' tools", "none", false, new Skill[0], 0);
    }
}
class Spy extends Background {
    public Spy() {
        super("Criminal (Spy)", "A crowbar, a set of dark common clothes including a hood", "Criminal Contact", "You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals. You know how to get messages to and from your contact, even over great distances; specifically, you know the local messengers, corrupt caravan masters, and seedy sailors who can deliver messages for you.", 15, "You have spent a lot of time among criminals and still have contacts within the criminal underworld. You're far closer than most people to the world of murder, theft, and violence that pervades the underbelly of civilization, and you have only barely survived up to this point. Although your capabilities are not much different from those of a burglar or smuggler, you learned and practiced them in a very different context: as an espionage agent. You might have been an officially sanctioned agent of the crown, or perhaps you sold the secrets you uncovered to the highest bidder.", new Skill[]{new Deception(), new Stealth()}, "1 type of gaming set and thieves' tools", "none", false, new Skill[0], 0);
    }
}

class Entertainer extends Background {
    public Entertainer() {
        super("Entertainer", "A musical instrument (one of your choice), the favor of an admirer (love letter, lock of hair, or trinket), a costume", "By Popular Demand", "You can always find a place to perform, usually in an inn or tavern but possibly with a circus, at a theater, or even in a noble's court. At such a place, you receive free lodging and food of a modest or comfortable standard (depending on the quality of the establishment), as long as you perform each night. In addition, your performance makes you something of a local figure. When strangers recognize you in a town where you have performed, they typically take a liking to you.", 15, "You thrive in front of an audience. You know how to entrance them, entertain them, and even inspire them. Your poetics can stir the hearts of those who hear you, awakening grief or joy, laughter or anger. Your music raises their spirits or captures their sorrow. Your dance steps captivate, your humor cuts to the quick. Whatever techniques you use, your art is your life.", new Skill[]{new Acrobatics(), new Performance()}, "Disguise Kit and 1 type of musical instrument", "none", false, new Skill[0], 0);
    }
}
class Gladiator extends Background {
    public Gladiator() {
        super("Gladiator", "An inexpensive but unusual weapon of choice, the favor of an admirer (love letter, lock of hair, or trinket), a costume", "By Popular Demand", "You can always find a place to perform, usually in an inn or tavern but possibly with a circus, at a theater, or even in a noble's court. At such a place, you receive free lodging and food of a modest or comfortable standard (depending on the quality of the establishment), as long as you perform each night. In addition, your performance makes you something of a local figure. When strangers recognize you in a town where you have performed, they typically take a liking to you.", 15, "You thrive in front of an audience. You know how to entrance them, entertain them, and even inspire them. A gladiator is as much an entertainer as any minstrel or circus performer trained to make the arts of combat into a spectacle the crowd can enjoy. This kind of flashy combat is your entertainer routine, though you might also have some skills as a tumbler or actor. Using your By Popular Demand feature, you can find a place to perform in any place that features combat for entertainment-perhaps a gladiatorial arena or secret pit fighting club. Whatever techniques you use, your art is your life.", new Skill[]{new Acrobatics(), new Performance()}, "Disguise Kit and 1 type of musical instrument", "none", false, new Skill[0], 0);
    }
}

class Faceless extends Background {
    public Faceless() {
        super("Faceless", "A disguise kit, a costume", "Dual Personalities", "Most of your fellow adventurers and the world know you as your persona. Those who seek to learn more about you—your weakness, your origins, your purpose—find themselves stymied by your disguise. Upon donning a disguise and behaving as your persona, you are unidentifiable as your true self. By removing your disguise and revealing your true face, you are no longer identifiable as your persona. This allows you to change appearances between your two personalities as often as you wish, using one to hide the other or serve as convenient camouflage. However, should someone realize the connection between your persona and your true self, your deception might lose its effectiveness.", 10, "Being who you are, you could never be a hero. Whether due to your class, your people, your family, or your sins, something about you prevents you from effectively pursuing the path you've chosen. Even so, that doesn't stop you. You've left your old face behind, taking on a new persona, becoming something more. Characters with the faceless background don a disguise—literally or otherwise—as they adventure. This persona might be dramatic or subtle. In a way, though, many characters have such larger than life personalities. Therefore, this background largely focuses on detailing the hero behind the mask.", new Skill[]{new Deception(), new Intimidation()}, "Disguise Kit", "1 language of choice", false, new Skill[0], 0);
    }
}

class FactionAgent extends Background {
    public FactionAgent() {
        super("Faction Agent", "The badge or emblem of your faction, a copy of a seminal faction text (or a code-book for a covert faction), a set of common clothes", "Safe Haven", "As a faction agent, you have access to a secret network of supporters and operatives who can provide assistance on your adventures. You know a set of secret signs and passwords you can use to identify such operatives, who can provide you with access to a hidden safe house, free room and board, or assistance in finding information. These agents never risk their lives for you or risk revealing their true identities.", 15, "Many organizations active in the North and across the face of Faerûn aren't bound by strictures of geography. These factions pursue their agendas without regard for political boundaries, and their members operate anywhere the organization deems necessary. These groups employ listeners, rumormongers, smugglers, sellswords, cache-holders (people who guard caches of wealth or magic for use by the faction's operatives), haven keepers, and message drop minders, to name a few. At the core of every faction are those who don't merely fulfill a small function for that organization, but who serve as its hands, head, and heart. As a prelude to your adventuring career (and in preparation for it), you served as an agent of a particular faction in Faerûn. You might have operated openly or secretly, depending on the faction and its goals, as well as how those goals mesh with your own. Becoming an adventurer doesn't necessarily require you to relinquish membership in your faction (though you can choose to do so), and it might enhance your status in the faction.", new Skill[]{new Insight()}, "none", "2 languages of choice", false, new Skill[0], 0);
    }
}

class FarTraveler extends Background {
    public FarTraveler() {
        super("Far Traveler", " One set of traveler's clothes, any one musical instrument or gaming set you are proficient with, poorly wrought maps from your homeland that depict where you are in Faerûn, a small piece of jewelry worth 10gp in the style of your homeland's craftsmanship", "All Eyes on You", "Your accent, mannerisms, figures of speech, and perhaps even your appearance all mark you as foreign. Curious glances are directed your way wherever you go, which can be a nuisance, but you also gain the friendly interest of scholars and others intrigued by far-off lands, to say nothing of everyday folk who are eager to hear stories of your homeland. You can parley this attention into access to people and places you might not otherwise have, for you and your traveling companions. Noble lords, scholars, and merchant princes, to name a few, might be interested in hearing about your distant homeland and people.", 5, "Almost all of the common people and other folk that one might encounter along the Sword Coast or in the North have one thing in common: they live out their lives without ever traveling more than a few miles from where they were born. You aren't one of those folk. You are from a distant place, one so remote that few of the common folk in the North realize that it exists, and chances are good that even if some people you meet have heard of your homeland, they know merely the name and perhaps a few outrageous stories. You have come to this part of Faerûn for your own reasons, which you might or might not choose to share. Although you will undoubtedly find some of this land's ways to be strange and discomfiting, you can also be sure that some things its people take for granted will be to you new wonders that you've never laid eyes on before. By the same token, you're a person of interest, for good or ill, to those around you almost anywhere you go.", new Skill[]{new Insight(), new Perception()}, "Any 1 musical instrument or gaming set of choice, likely something native to your homeland", "1 language of choice", false, new Skill[0], 0);
    }
}

class Feylost extends Background {
    public Feylost() {
        super("Feylost", "A musical instrument (one of your choice), a set of traveler's clothes, three trinkets", "Feywild Connection", "Your mannerisms and knowledge of fey customs are recognized by natives of the Feywild, who see you as one of their own. Because of this, friendly Fey creatures are inclined to come to your aid if you are lost or need help in the Feywild.", 8, "You grew up in the Feywild after disappearing from your home plane as a child. Perhaps you were spirited away by kindly Fey who thought you were destined for great things. Perhaps you stumbled through a Fey crossing by chance during a twilight stroll in the woods. Perhaps you were kidnapped by evil Fey but escaped from their clutches. Whatever the manner of your disappearance, you gradually fell under the Feywild's spell and learned a little about the nature of the mercurial tricksters that dwell there. When you finally returned to your home plane, you did not come back unchanged. You are haunted by the fact the Feywild-a mirror world hidden behind a mere twist of perception-is only a hair's breadth away. Although your memories of the Feywild grow fainter with each passing day, your heart swells with a mixture of fear and joy at the prospect of one day venturing back to the Plane of Faerie-your home away from home.", new Skill[]{new Deception(), new Survival()}, "1 type of musical instrument", "1 language of the following: Elvish, Gnomish, Goblin, Sylvan", false, new Skill[0], 0);
    }
}

class Fisher extends Background {
    public Fisher() {
        super("Fisher", " Fishing tackle, a net, a favorite fishing lure or oiled leather wading boots, a set of traveler's clothes", "Harvest the Water", "You gain advantage on ability checks made using fishing tackle. If you have access to a body of water that sustains marine life, you can maintain a moderate lifestyle while working as a fisher, and you can catch enough food to feed yourself and up to ten other people each day.", 10, "You have spent your life aboard fishing vessels or combing the shallows for the bounty of the ocean. Perhaps you were born into a family of fisher folk, working with your kin to feed your village. Maybe the job was a means to an end - a way out of an undesirable circumstance that forced you to take up life aboard a ship. Regardless of how you began, you soon fell in love with the sea, the art of fishing, and the promise of the eternal horizon.", new Skill[]{new History(), new Survival()}, "none", "1 language of choice", false, new Skill[0], 0);
    }
}

class FolkHero extends Background {
    public FolkHero() {
        super("Folk Hero", "A set of artisan's tools (one of your choice), a shovel, an iron pot, and a set of common clothes", "Rustic Hospitality", "Since you come from the ranks of the common folk, you fit in among them with ease. You can find a place to hide, rest, or recuperate among other commoners, unless you have shown yourself to be a danger to them. They will shield you from the law or anyone else searching for you, though they will not risk their lives for you.", 10, "You come from a humble social rank, but you are destined for so much more. Already the people of your home village regard you as their champion, and your destiny calls you to stand against the tyrants and monsters that threaten the common folk everywhere.", new Skill[]{new AnimalHandling(), new Survival()}, "One type of artisan's tools, vehicles (land)", "none", false, new Skill[0], 0);
    }
}

class GuildArtisan extends Background {
    public GuildArtisan() {
        super("Guild Artisan", "A set of artisan's tools (one of your choice), a letter of introduction from your guild, and a set of traveler's clothes", "Guild Membership", "As an established and respected member of a guild, you can rely on certain benefits that membership provides. Your fellow guild members will provide you with lodging and food if necessary, and pay for your funeral if needed. In some cities and towns, a guildhall offers a central place to meet other members of your profession, which can be a good place to meet potential patrons, allies, or hirelings. Guilds often wield tremendous political power. If you are accused of a crime, your guild will support you if a good case can be made for your innocence or the crime is justifiable. You can also gain access to powerful political figures through the guild, if you are a member in good standing. Such connections might require the donation of money or magic items to the guild's coffers. You must pay dues of 5 gp per month to the guild. If you miss payments, you must make up back dues to remain in the guild's good graces.", 15, "You are a member of an artisan's guild, skilled in a particular field and closely associated with other artisans. You are a well-established part of the mercantile world, freed by talent and wealth from the constraints of a feudal social order. You learned your skills as an apprentice to a master artisan, under the sponsorship of your guild, until you became a master in your own right.", new Skill[]{new Insight(), new Persuasion()}, "One type of artisan's tools", "1 language of choice", false, new Skill[0], 0);
    }
}

class HauntedOne extends Background {
    public HauntedOne() {
        super("Haunted One", "A monster hunter’s pack, and one trinket of special significance (choose one or roll on the Gothic Trinkets table). Also gain a set of set of common clothes", "Heart of Darkness", "Those who look into your eyes can see that you have faced unimaginable horror and that you are no stranger to darkness. Though they might fear you, commoners will extend you every courtesy and do their utmost to help you. Unless you have shown yourself to be a danger to them, they will even take up arms to fight alongside you, should you find yourself facing an enemy alone.", 0.1, "You are haunted by something so terrible that you dare not speak of it. You’ve tried to bury it and run away from it, to no avail. Whatever this thing is that haunts you can’t be slain with a sword or banished with a spell. It might come to you as a shadow on the wall, a bloodcurdling nightmare, a memory that refuses to die, or a demonic whisper in the dark. The burden has taken its toll, isolating you from most people and making you question your sanity. You must find a way to overcome it before it destroys you.", new Skill[0], "none", "2 languages of choice, 1 being an exotic language (Abyssal, Celestial, Deep Speech, Draconic, Infernal, Primordial, Sylvan, or Undercommon)", true, new Skill[]{new Arcana(), new Investigation(), new Religion(), new Survival()}, 2);
    }
}

class Hermit extends Background {
    public Hermit() {
        super("Hermit", "A scroll case stuffed full of notes from your studies or prayers, a winter blanket, a set of common clothes, an herbalism kit", "Discovery", "The quiet seclusion of your extended hermitage gave you access to a unique and powerful discovery. The exact nature of this revelation depends on the nature of your seclusion. It might be a great truth about the cosmos, the deities, the powerful beings of the outer planes, or the forces of nature. It could be a site that no one else has ever seen. You might have uncovered a fact that has long been forgotten, or unearthed some relic of the past that could rewrite history. It might be information that would be damaging to the people who or consigned you to exile, and hence the reason for your return to society. Work with your DM to determine the details of your discovery and its impact on the campaign.", 5, "You lived in seclusion – either in a sheltered community such as a monastery, or entirely alone – for a formative part of your life. In your time apart from the clamor of society, you found quiet, solitude, and perhaps some of the answers you were looking for.", new Skill[]{new Medicine(), new Religion()}, "Herbalism kit", "1 language of choice", false, new Skill[0], 0);
    }
}

class Inheritor extends Background {
    public Inheritor() {
        super("Inheritor", "Your inheritance, a set of traveler's clothes, the tool you choose for this background’s tool proficiency", "Inheritance", "Choose or randomly determine your inheritance from among the possibilities in the table below. Work with your DM to come up with details: Why is your inheritance so important, and what is its full story? You might prefer for the DM to invent these details as part of the game, allowing you to learn more about your inheritance as your character does. The DM is free to use your inheritance as a story hook, sending you on quests to learn more about its history or true nature, or confronting you with foes who want to claim it for themselves or prevent you from learning what you seek. The DM also determines the properties of your inheritance and how they figure into the item's history and importance. For instance, the object might be a minor magic item, or one that begins with a modest ability and increases in potency with the passage of time. Or, the true nature of your inheritance might not be apparent at first and is revealed only when certain conditions are met. When you begin your adventuring career, you can decide whether to tell your companions about your inheritance right away. Rather than attracting attention to yourself, you might want to keep your inheritance a secret until you learn more about what it means to you and what it can do for you.\n" +
                "  d8 \tObject or Item\n" +
                "   1 \tA document such as a map, a letter, or a journal\n" +
                "   2-3 \tA trinket\n" +
                "   4 \tAn article of clothing\n" +
                "   5 \tA piece of jewelry\n" +
                "   6 \tAn arcane book or formulary\n" +
                "   7 \tA written story, song, poem, or secret\n" +
                "   8 \tA tattoo or other body marking", 15, "You are the heir to something of great value – not mere coin or wealth, but an object that has been entrusted to you and you alone. Your inheritance might have come directly to you from a member of your family, by right of birth, or it could have been left to you by a friend, a mentor, a teacher, or someone else important in your life. The revelation of your inheritance changed your life, and might have set you on the path to adventure, but it could also come with many dangers, including those who covet your gift and want to take it from you – by force, if need be.", new Skill[]{new Survival()}, "1 choice of a gaming set of musical instrument", "1 language of choice", true, new Skill[]{new Arcana(), new History(), new Religion()}, 1);
    }
}

class Investigator extends Background {
    public Investigator() {
        super("Investigator", "A magnifying glass, evidence from a past case (choose one or roll for a trinket from the Horror Trinkets table) a set of common clothes", "Official Inquiry", "You're experienced at gaining access to people and places to get the information you need. Through a combination of fast-talking, determination, and official-looking documentation, you can gain access to a place or an individual related to a crime you're investigating. Those who aren't involved in your investigation avoid impeding you or pass along your requests. Additionally, local law enforcement has firm opinions about you, viewing you as either a nuisance or one of their own.", 10,"You relentlessly seek the truth. Perhaps you're motivated by belief in the law and a sense of universal justice, or maybe that very law has failed you and you seek to make things right. You could have witnessed something remarkable or terrible, and now you must know more about this hidden truth. Or maybe you're a detective for hire, uncovering secrets for well-paying clients. Whether the mysteries you're embroiled in are local crimes or realm-spanning conspiracies, you're driven by a personal need to hunt down even the most elusive clues and reveal what others would keep hidden in the shadows.", new Skill[0], "Disguise kit and Thieves' tools", "none", true, new Skill[]{new Insight(), new Investigation(), new Perception()}, 2);
    }
}

class Marine extends Background {
    public Marine() {
        super("Marine", "A dagger that belonged to a fallen comrade, a folded rag emblazoned with the symbol of your ship or company, a set of traveler's clothes", "Steady", "You can move twice the normal amount of time (up to 16 hours) each day before being subject to the effect of a forced march (see \"Travel Pace\" in chapter 8 of the Player's Handbook). Additionally, you can automatically find a safe route to land a boat on shore, provided such a route exists.", 10, "You were trained for battle on sandy beaches and rocky shores. You have launched midnight raids from swift ships whose names evoke terror in the hearts of your adversaries. The water is your second home, the rain your shelter, and the crashing waves your battle cry.", new Skill[]{new Athletics(), new Survival()}, "Vehicles (land and water)", "none", false, new Skill[0], 0);
    }
}

class MercenaryVeteran extends Background {
    public MercenaryVeteran() {
        super("Mercenary Veteran", "A uniform of your company (traveler's clothes in quality), an insignia of your rank, a gaming set of your choice", "Mercenary Life", "You know the mercenary life as only someone who has experienced it can. You are able to identify mercenary companies by their emblems, and you know a little about any such company, including the names and reputations of its commanders and leaders, and who has hired them recently. You can find the taverns and festhalls where mercenaries abide in any area, as long as you speak the language. You can find mercenary work between adventures sufficient to maintain a comfortable lifestyle.", 10, "As a sell-sword who fought battles for coin, you're well acquainted with risking life and limb for a chance at a share of treasure. Now, you look forward to fighting foes and reaping even greater rewards as an adventurer. Your experience makes you familiar with the ins and outs of mercenary life, and you likely have harrowing stories of events on the battlefield. You might have served with a large outfit such as the Zhentarim or the soldiers of Mintarn, or a smaller band of sell-swords, maybe even more than one. See the \"Mercenaries of the North\" section below for a collection of possibilities. Now you're looking for something else, perhaps greater reward for the risks you take, or the freedom to choose your own activities. For whatever reason, you're leaving behind the life of a soldier for hire, but your skills are undeniably suited for battle, so now you fight on in a different way.", new Skill[]{new Athletics(), new Perception()}, "1 choice of gaming set and vehicles (land)", "none", false, new Skill[0], 0);
    }
}

class Noble extends Background  {
    public Noble() {
        super("Noble", "A set of fine clothes, a signet ring, a scroll of pedigree", "Position of Privilege", "Thanks to your noble birth, people are inclined to think the best of you. You are welcome in high society, and people assume you have the right to be wherever you are. The common folk make every effort to accommodate you and avoid your displeasure, and other people of high birth treat you as a member of the same social sphere. You can secure an audience with a local noble if you need to.", 25, "You understand wealth, power, and privilege. You carry a noble title, and your family owns land, collects taxes, and wields significant political influence. You might be a pampered aristocrat unfamiliar with work or discomfort, a former merchant just elevated to the nobility, or a disinherited scoundrel with a disproportionate sense of entitlement. Or you could be an honest, hard-working landowner who cares deeply about the people who live and work on your land, keenly aware of your responsibility to them. Work with your DM to come up with an appropriate title and determine how much authority that title carries. A noble title doesn't stand on its own-it's connected to an entire family, and whatever title you hold, you will pass it down to your own children. Not only do you need to determine your noble title, but you should also work with the DM to describe your family and their influence on you.", new Skill[]{new History(), new Persuasion()}, "1 choice of gaming set", "1 language of choice", false, new Skill[0], 0);
    }
}
class Knight extends Background  {
    public Knight() {
        super("Knight", "A set of fine clothes, a signet ring, a scroll of pedigree", "Retainers", "You have the service of three retainers loyal to your family. These retainers can be attendants or messengers, and one might be a majordomo. Your retainers are commoners who can perform mundane tasks for you, but they do not fight for you, will not follow you into obviously dangerous areas (such as dungeons), and will leave if they are frequently endangered or abused.", 25, "A knighthood is among the lowest noble titles in most societies, but it can be a path to higher status. If you wish to be a knight, choose the Retainers feature below instead of the Position of Privilege feature. One of your commoner retainers is replaced by a noble who serves as your squire, aiding you in exchange for training on his or her own path to knighthood. Your two remaining retainers might include a groom to care for your horse and a servant who polishes your armor (and even helps you put it on). As an emblem of chivalry and the ideals of courtly love, you might include among your equipment a banner or other token from a noble lord or lady to whom you have given your heart – in a chaste sort of devotion. (This person could be your bond.)", new Skill[]{new History(), new Persuasion()}, "1 choice of gaming set", "1 language of choice", false, new Skill[0], 0);
    }
}

class Outlander extends Background {
    public Outlander() {
        super("Outlander", "A staff, a hunting trap, a trophy from an animal you killed, a set of traveler's clothes", "Wanderer", "You have an excellent memory for maps and geography, and you can always recall the general layout of terrain, settlements, and other features around you. In addition, you can find food and fresh water for yourself and up to five other people each day, provided that the land offers berries, small game, water, and so forth.", 10, "You grew up in the wilds, far from civilization and the comforts of town and technology. You've witnessed the migration of herds larger than forests, survived weather more extreme than any city-dweller could comprehend, and enjoyed the solitude of being the only thinking creature for miles in any direction. The wilds are in your blood, whether you were a nomad, an explorer, a recluse, a hunter-gatherer, or even a marauder. Even in places where you don't know the specific features of the terrain, you know the ways of the wild.", new Skill[]{new Athletics(), new Survival()}, "1 musical instrument of choice", "1 language of choice", false, new Skill[0], 0);
    }
}

class Sage extends Background {
    public Sage() {
        super("Sage", " A bottle of ink, a quill, a small knife, a letter from a dead colleague posing a question you have not yet been able to answer, a set of common clothes", "Researcher", "When you attempt to learn or recall a piece of lore, if you do not know that information, you often know where and from whom you can obtain it. Usually, this information comes from a library, scriptorium, university, or a sage or other learned person or creature. Your DM might rule that the knowledge you seek is secreted away in an almost inaccessible place, or that it simply cannot be found. Unearthing the deepest secrets of the multiverse can require an adventure or even a whole campaign.", 10, "You spent years learning the lore of the multiverse. You scoured manuscripts, studied scrolls, and listened to the greatest experts on the subjects that interest you. Your efforts have made you a master in your fields of study.", new Skill[]{new Arcana(), new History()}, "none", "2 languages of choice", false, new Skill[0], 0);
    }
}

class Sailor extends Background {
    public Sailor() {
    super("Sailor", "A belaying pin (club), 50 feet of silk rope, a lucky charm such as a rabbit foot or a small stone with a hole in the center, a set of common clothes", "Ship's Passage", "When you need to, you can secure free passage on a sailing ship for yourself and your adventuring companions. You might sail on the ship you served on, or another ship you have good relations with (perhaps one captained by a former crewmate). Because you're calling in a favor, you can't be certain of a schedule or route that will meet your every need. Your DM will determine how long it takes to get where you need to go. In return for your free passage, you and your companions are expected to assist the crew during the voyage.", 10, "You sailed on a seagoing vessel for years. In that time, you faced down mighty storms, monsters of the deep, and those who wanted to sink your craft to the bottomless depths. Your first love is the distant line of the horizon, but the time has come to try your hand at something new. Discuss the nature of the ship you previously sailed with your DM. Was it a merchant ship, a naval vessel, a ship of discovery, or a pirate ship? How famous (or infamous) is it? Is it widely traveled? Is it still sailing, or is it missing and presumed lost with all hands?", new Skill[]{new Athletics(), new Perception()}, "Navigator's tools and vehicles (water)", "none", false, new Skill[0], 0);
    }
}
class Pirate extends Background {
    public Pirate() {
        super("Pirate", "A belaying pin (club), 50 feet of silk rope, a lucky charm such as a rabbit foot or a small stone with a hole in the center, a set of common clothes", "Bad Reputation", "No matter where you go, people are afraid of you due to your reputation. When you are in a civilized settlement, you can get away with minor criminal offenses, such as refusing to pay for food at a tavern or breaking down doors at a local shop, since most people will not report your activity to the authorities.", 10, "You spent your youth under the sway of a dread pirate, a ruthless cutthroat who taught you how to survive in a world of sharks and savages. You've indulged in larceny on the high seas and sent more than one deserving soul to a briny grave. Fear and bloodshed are no strangers to you, and you've garnered a somewhat unsavory reputation in many a port town.", new Skill[]{new Athletics(), new Perception()}, "Navigator's tools and vehicles (water)", "none", false, new Skill[0], 0);
    }
}

class Shipwright extends Background {
    public Shipwright() {
        super("Shipwright", "A set of well-loved carpenter's tools, a blank book, 1 ounce of ink, an ink pen, a set of traveler's clothes", "I'll Patch It!", "Provided you have carpenter's tools and wood, you can perform repairs on a water vehicle. When you use this ability, you restore a number of hit points to the hull of a water vehicle equal to 5 × your proficiency modifier. A vehicle cannot be patched by you in this way again until after it has been pulled ashore and fully repaired.", 10, "You have sailed into war on the decks of great ships, patching their hulls with soup bowls and prayers. You once helped build a fishing vessel that single-handedly saved a town from starvation. You have seen a majestic prow in your dreams that you have not been able to replicate in wood. Since childhood, you have loved the water and have been captivated by the many vessels that travel on it.", new Skill[]{new History(), new Perception()}, "Carpenter's tools and vehicles (water)", "none", false, new Skill[0], 0);
    }
}

class Smuggler extends Background {
    public Smuggler() {
        super("Smuggler", "A fancy leather vest or a pair of leather boots, a set of common clothes", "Down Low", "You are acquainted with a network of smugglers who are willing to help you out of tight situations. While in a particular town, city, or other similarly sized community (DM's discretion), you and your companions can stay for free in safe houses. Safe houses provide a poor lifestyle. While staying at a safe house, you can choose to keep your presence (and that of your companions) a secret.", 15, "On a rickety barge, you carried a hundred longswords in fish barrels right past the dock master's oblivious lackeys. You have paddled a riverboat filled with stolen elven wine under the gaze of the moon and sold it for twice its value in the morning. In your more charitable times, you have transported innocents out of war zones or helped guide herd animals to safety on the banks of a burning river.", new Skill[]{new Athletics(), new Deception()}, "Vehicles (water)", "none", false, new Skill[0], 0);
    }
}

class Soldier extends Background {
    public Soldier() {
        super("Soldier", "An insignia of rank, a trophy taken from a fallen enemy (a dagger, broken blade, or piece of a banner), a set of bone dice or a deck of cards, a set of common clothes", "Military Rank", "You have a military rank from your career as a soldier. Soldiers loyal to your former military organization still recognize your authority and influence, and they defer to you if they are of a lower rank. You can invoke your rank to exert influence over other soldiers and requisition simple equipment or horses for temporary use. You can also usually gain access to friendly military encampments and fortresses where your rank is recognized.", 10, "War has been your life for as long as you care to remember. You trained as a youth, studied the use of weapons and armor, learned basic survival techniques, including how to stay alive on the battlefield. You might have been part of a standing national army or a mercenary company, or perhaps a member of a local militia who rose to prominence during a recent war. When you choose this background, work with your DM to determine which military organization you were a part of, how far through its ranks you progressed, and what kind of experiences you had during your military career. Was it a standing army, a town guard, or a village militia? Or it might have been a noble's or merchant's private army, or a mercenary company.", new Skill[]{new Athletics(), new Intimidation()}, "1 choice of gaming set and vehicles (land)", "none", false, new Skill[0], 0);
    }
}

class UrbanBountyHunter extends Background {
    public UrbanBountyHunter() {
        super("Urban Bounty Hunter", "A set of clothes appropriate to your duties", "Ear to the Ground", "You are in frequent contact with people in the segment of society that your chosen quarries move through. These people might be associated with the criminal underworld, the rough-and-tumble folk of the streets, or members of high society. This connection comes in the form of a contact in any city you visit, a person who provides information about the people and places of the local area.", 20, "Before you became an adventurer, your life was already full of conflict and excitement, because you made a living tracking down people for pay. Unlike some people who collect bounties, though, you aren't a savage who follows quarry into or through the wilderness. You're involved in a lucrative trade, in the place where you live, that routinely tests your skills and survival instincts. What's more, you aren't alone, as a bounty hunter in the wild would be: you routinely interact with both the criminal subculture and other bounty hunters, maintaining contacts in both areas to help you succeed. You might be a cunning thief-catcher, prowling the rooftops to catch one of the myriad burglars of the city. Perhaps you are someone who has your ear to the street, aware of the doings of thieves' guilds and street gangs. You might be a \"velvet mask\" bounty hunter, one who blends in with high society and noble circles in order to catch the criminals that prey on the rich, whether pickpockets or con artists. The community where you plied your trade might have been one of Faenûn's great metropolises, such as Waterdeep or Baldur's Gate, or a less populous location, perhaps Luskan or Yartar – any place that's large enough to have a steady supply of potential quarries. As a member of an adventuring party, you might find it more difficult to pursue a personal agenda that doesn't fit with the group's objectives – but on the other hand, you can take down much more formidable targets with the help of your companions.", new Skill[0], "Choose 2 from among 1 type of gaming set, 1 musical instrument, and Thieves' tools", "none", true, new Skill[]{new Deception(), new Insight(), new Persuasion(), new Stealth()}, 2);
    }
}

class Urchin extends Background {
    public Urchin() {
        super("Urchin", "A small knife, a map of the city you grew up in, a pet mouse, a token to remember your parents by, a set of common clothes", "City Secrets", "You know the secret patterns and flow to cities and can find passages through the urban sprawl that others would miss. When you are not in combat, you (and companions you lead) can travel between any two locations in the city twice as fast as your speed would normally allow.", 10, "You grew up on the streets alone, orphaned, and poor, You had no one to watch over you or to provide for you, so you learned to provide for yourself. You fought fiercely over food and kept a constant watch out for other desperate souls who might steal from you. You slept on rooftops and in alleyways, exposed to the elements, and endured sickness without the advantage of medicine or a place to recuperate. You've survived despite all odds, and did so through cunning, strength, speed, or some combination of each. You begin your adventuring career with enough money to live modestly but securely for at least ten days. How did you come by that money? What allowed you to break free of your desperate circumstances and embark on a better life?", new Skill[]{new SleightOfHand(), new Stealth()}, "Disguise kit and Thieves' tools", "none", false, new Skill[0], 0);
    }
}

class WaterdhavianNoble extends Background {
    public WaterdhavianNoble() {
        super("Waterdhavian Noble", "A set of fine clothes, a signet ring or brooch, a scroll of pedigree, a skin of fine zzar or wine", "Kept in Style", "While you are in Waterdeep or elsewhere in the North your house sees to your everyday needs. Your name and signet are sufficient to cover most of your expenses; the inns, taverns, and festhalls you frequent are glad to record your debt and send an accounting to your family's estate in Waterdeep to settle what you owe. This advantage enables you to live a comfortable lifestyle without having to pay 2 gp a day for it, or reduces the cost of a wealthy or aristocratic lifestyle by that amount. You may not maintain a less affluent lifestyle and use the difference as income – the benefit is a line of credit, not an actual monetary reward.", 20, "You are a scion of one of the great noble families of Waterdeep. Human families who jealously guard their privilege and place in the City of Splendors, Waterdhavian nobles have a reputation across Faerûn for being eccentric, spoiled, venal, and, above all else, rich. Whether you are a shining example of the reason for this reputation or one who proves the rule by being an exception, people expect things of you when they know your surname and what it means. Your reasons for taking up adventuring likely involve your family in some way: Are you the family rebel, who prefers delving in filthy dungeons to sipping zzar at a ball? Or have you taken up sword or spell on your family's behalf, ensuring that they have someone of renown to see to their legacy? Work with your DM to come up with the family you are part of – there are around seventy-five lineages in Waterdeep, each with its own financial interests, specialties, and schemes. You might be part of the main line of your family, possibly in line to become its leader one day. Or you might be one of any number of cousins, with less prestige but also less responsibility.", new Skill[]{new History(), new Persuasion()}, "1 choice of gaming set or musical instrument", "1 language of choice", false, new Skill[0], 0);
    }
}

class WitchlightHand extends Background {
    public WitchlightHand() {
        super("Witchlight Hand", "A disguise kit or a musical instrument of your choice, a deck of cards, a carnival uniform or costume, one trinket", "Carnival Fixture", "The Witchlight Carnival provides you with free, modest lodging and food. In addition, you may wander about the carnival and partake of its many wonders at no cost to you, provided you don't disrupt its shows or cause any other trouble.", 8, "You crept into the Witchlight Carnival as a child or youth and never looked back, earning a place among those who work behind the scenes to keep the carnival in business. As a hand, you work hard and party hard. The carnival has borne you to many fantastic worlds, circling back around to your home world once every eight years, but you know almost nothing about these worlds because you spend all your time in the carnival. You know the other hands well, but the carnival's owners-Mister Witch and Mister Light-remain mysterious to you even after all these years. Maybe you joined the carnival to escape a dismal life at home, or maybe you were enchanted by the idea of visiting new places or the dream of becoming one of the carnival's star attractions. Now that you're older, carnival life has lost some of its appeal. The daily routine has grown tedious, the cyclical nature of the carnival's journey monotonous. The carnival no longer fills your heart with a sense of wonder. Perhaps greater adventures await you beyond the carnival's gates.", new Skill[]{new Performance(), new SleightOfHand()}, "Dishuise kit or 1 choice of musical instrument", "1 language of choice", false, new Skill[0], 0);
    }
}